version: '3.8'

services:

  izumrudny_gorod_app:
    container_name: hrspace
    build: ./
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: "db"
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgresql/data/